Invalid HTTP_HOST header: '18.230.216.176:8000'. You may need to add '18.230.216.176' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '18.230.216.176:8000'. You may need to add '18.230.216.176' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '18.230.216.176:8000'. You may need to add '18.230.216.176' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '18.230.216.176:8000'. You may need to add '18.230.216.176' to ALLOWED_HOSTS.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\backend\accounts\views.py", line 58, in create
    password=data['password'],
             ~~~~^^^^^^^^^^^^
KeyError: 'password'
"POST /api/usuarios/ HTTP/1.1" 500 97549
Internal Server Error: /api/auth/login/
Traceback (most recent call last):
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\backend\accounts\views.py", line 26, in login
    user = authenticate(request, email=email, password=password)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 70, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
                                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 29, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 23, in load_backend
    return import_string(path)()
           ~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Program Files\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'path'
"POST /api/auth/login/ HTTP/1.1" 500 147680
Internal Server Error: /api/auth/login/
Traceback (most recent call last):
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\backend\accounts\views.py", line 26, in login
    user = authenticate(request, email=email, password=password)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 70, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
                                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 29, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 23, in load_backend
    return import_string(path)()
           ~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Program Files\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'path'
"POST /api/auth/login/ HTTP/1.1" 500 146635
Internal Server Error: /api/auth/login/
Traceback (most recent call last):
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\backend\accounts\views.py", line 26, in login
    user = authenticate(request, email=email, password=password)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 70, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
                                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 29, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 23, in load_backend
    return import_string(path)()
           ~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Program Files\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'path'
"POST /api/auth/login/ HTTP/1.1" 500 146635
Internal Server Error: /api/auth/login/
Traceback (most recent call last):
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\backend\accounts\views.py", line 26, in login
    user = authenticate(request, email=email, password=password)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 70, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
                                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 29, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 23, in load_backend
    return import_string(path)()
           ~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Program Files\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'path'
"POST /api/auth/login/ HTTP/1.1" 500 146635
Internal Server Error: /api/auth/login/
Traceback (most recent call last):
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\backend\accounts\views.py", line 26, in login
    user = authenticate(request, email=email, password=password)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 70, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
                                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 29, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 23, in load_backend
    return import_string(path)()
           ~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Program Files\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'path'
"POST /api/auth/login/ HTTP/1.1" 500 146635
Internal Server Error: /api/auth/login/
Traceback (most recent call last):
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\backend\accounts\views.py", line 26, in login
    user = authenticate(request, email=email, password=password)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 70, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
                                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 29, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 23, in load_backend
    return import_string(path)()
           ~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Program Files\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'path'
"POST /api/auth/login/ HTTP/1.1" 500 146635
Internal Server Error: /api/auth/login/
Traceback (most recent call last):
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\backend\accounts\views.py", line 26, in login
    user = authenticate(request, email=email, password=password)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 70, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
                                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 29, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 23, in load_backend
    return import_string(path)()
           ~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Program Files\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'path'
"POST /api/auth/login/ HTTP/1.1" 500 147701
Internal Server Error: /api/auth/login/
Traceback (most recent call last):
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\backend\accounts\views.py", line 26, in login
    user = authenticate(request, email=email, password=password)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 70, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
                                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 29, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 23, in load_backend
    return import_string(path)()
           ~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Program Files\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'path'
"POST /api/auth/login/ HTTP/1.1" 500 146635
Internal Server Error: /api/auth/login/
Traceback (most recent call last):
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\backend\accounts\views.py", line 26, in login
    user = authenticate(request, email=email, password=password)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 70, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
                                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 29, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 23, in load_backend
    return import_string(path)()
           ~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Yorsh\Desktop\Proyect_G\Proyect\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Program Files\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'path'
"POST /api/auth/login/ HTTP/1.1" 500 146635
You're accessing the development server over HTTPS, but it only supports HTTP.
